run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  fast: true
  disable-all: true
  enable:
    - gci
    - gofmt
    - gosec
    - errcheck
    - stylecheck
#    - govet
#    - gosimple
#    - staticcheck

linters-settings:
  staticcheck:
    checks: [ "all"]
  gci:
    custom-order: true
    sections:
      - standard
      - blank
      - dot
      - prefix(commons)
      - prefix(user-ms)
      - default
    skip-generated: true

issues:
  fix: true
  exclude:
    - '.*\.pb\.go$'
    - '.*_test\.go$'
    - '.*_mock\.go$'
