global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
#  - "first.rules"
#  - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

#  - job_name: 'auth-ms'
#    static_configs:
#      - targets: ['auth-ms:8080'] # TODO: not work
#
#  - job_name: 'user-ms'
#    static_configs:
#      - targets: ['user-ms:8080'] # TODO: not work
