global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'auth-ms'
    static_configs:
      - targets: ['localhost:8081'] # TODO: not work
  - job_name: 'user-ms'
    static_configs:
      - targets: ['localhost:8082'] # TODO: not work
