global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
  format: json
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    filename: ./dynamic_conf.yml
    watch: true
  docker:
    exposedByDefault: false # this make services have to enable (allow) Traefik to manage them
    network: backend
