#  traefik.yml, this is the Traefik static configuration.

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG
  format: json

api:
  dashboard: true
  insecure: true

# We must define entryPoints and providers on the static configuration file.

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    # It is recommended to use directory.
    directory: /etc/traefik/configs
    watch: true
