#  traefik.yml, this is the Traefik static configuration.

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG
  format: json

# We must define entryPoints and providers on the static configuration file.

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

api:
  dashboard: true   # https://doc.traefik.io/traefik/operations/api/#dashboard
  insecure: true    # https://doc.traefik.io/traefik/operations/api/#insecure

ping: {}

providers:
  file:
    directory: /etc/traefik/configs   # It is recommended to use directory.
    watch: true

# install plugins

experimental:
  plugins:
    jwt:
      moduleName: github.com/traefik-plugins/traefik-jwt-plugin
      version: v0.7.1
