run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  fast: true
  presets:
    - format
    - error
    - unused
    - comment
    - metalinter
    - complexity
    - performance
    - test
  disable-all: true
  enable:
    - gci
    - goimports     # Check import statements are formatted according to the 'goimport' command
    - gofmt
    - errcheck
    - stylecheck
    - gosec         # Detects security issues.
#    - gosimple      # Aims to simplify code by suggesting more concise or idiomatic ways of writing it.
#    - govet         # Performs a wide range of checks, including potential race conditions, unused variables, and interface mismatches.
#    - staticcheck   # Goes beyond basic `govet` checks. It analyzes code for potential errors and performance issues that are difficult to detect at runtime.

linters-settings:
  staticcheck:
    checks: [ "*"]
  gci:
    custom-order: true
    sections:
      - standard
      - blank
      - dot
      - prefix(commons)
      - prefix(auth-ms)
      - default
    skip-generated: true

issues:
  fix: true
  exclude:
    - '.*\.pb\.go$'
    - '.*_test\.go$'
    - '.*_mock\.go$'
  exclude-dirs:
    - pkg/protos
