// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dao

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error)
	ClearCart(ctx context.Context, cartID uuid.UUID) error
	CreateCart(ctx context.Context, userID uuid.UUID) (Cart, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	DeleteCart(ctx context.Context, id uuid.UUID) error
	DeleteOrder(ctx context.Context, id uuid.UUID) error
	GetCart(ctx context.Context, userID uuid.UUID) (GetCartRow, error)
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (CartItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
