[package]
name = "product-ms"
version = "0.1.0"
edition = "2021"

[dependencies]
ferris-says = "0.3.2"
lazy_static = "1.5.0"
postgres = "0.19.9"
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.135"
