// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dao

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddDiscountCategory(ctx context.Context, arg *AddDiscountCategoryParams) error
	AddDiscountProduct(ctx context.Context, arg *AddDiscountProductParams) error
	AddProductCategory(ctx context.Context, arg *AddProductCategoryParams) error
	AddVoucherCategory(ctx context.Context, arg *AddVoucherCategoryParams) error
	AddVoucherProduct(ctx context.Context, arg *AddVoucherProductParams) error
	CountActiveDiscounts(ctx context.Context, storeID uuid.UUID) (int64, error)
	CountActiveVouchers(ctx context.Context, storeID uuid.UUID) (int64, error)
	CountCategoryProducts(ctx context.Context, categoryID uuid.UUID) (int64, error)
	CountDiscounts(ctx context.Context, storeID uuid.UUID) (int64, error)
	CountProductVariants(ctx context.Context, productID uuid.UUID) (int64, error)
	CountProducts(ctx context.Context, storeID uuid.UUID) (int64, error)
	CountProductsByStatus(ctx context.Context, arg *CountProductsByStatusParams) (int64, error)
	CountStoreCategories(ctx context.Context, storeID uuid.UUID) (int64, error)
	CountStoreCategoriesByParent(ctx context.Context, arg *CountStoreCategoriesByParentParams) (int64, error)
	CountStores(ctx context.Context) (int64, error)
	CountStoresByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CountVouchers(ctx context.Context, storeID uuid.UUID) (int64, error)
	CreateDiscount(ctx context.Context, arg *CreateDiscountParams) (*Discount, error)
	CreateProduct(ctx context.Context, arg *CreateProductParams) (*Product, error)
	CreateProductImage(ctx context.Context, arg *CreateProductImageParams) (*ProductImage, error)
	CreateProductVariant(ctx context.Context, arg *CreateProductVariantParams) (*ProductVariant, error)
	CreateStore(ctx context.Context, arg *CreateStoreParams) (*Store, error)
	CreateStoreCategory(ctx context.Context, arg *CreateStoreCategoryParams) (*StoreCategory, error)
	CreateVoucher(ctx context.Context, arg *CreateVoucherParams) (*Voucher, error)
	DeleteDiscount(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteProductImage(ctx context.Context, id uuid.UUID) error
	DeleteProductImages(ctx context.Context, productID uuid.UUID) error
	DeleteProductVariant(ctx context.Context, id uuid.UUID) error
	DeleteProductVariants(ctx context.Context, productID uuid.UUID) error
	DeleteStore(ctx context.Context, id uuid.UUID) error
	DeleteStoreCategory(ctx context.Context, id uuid.UUID) error
	DeleteVariantImages(ctx context.Context, variantID uuid.NullUUID) error
	DeleteVoucher(ctx context.Context, id uuid.UUID) error
	GetCategoryProducts(ctx context.Context, arg *GetCategoryProductsParams) ([]*Product, error)
	GetDiscount(ctx context.Context, id uuid.UUID) (*Discount, error)
	GetDiscountByCode(ctx context.Context, arg *GetDiscountByCodeParams) (*Discount, error)
	GetDiscountCategories(ctx context.Context, discountID uuid.UUID) ([]*StoreCategory, error)
	GetDiscountProducts(ctx context.Context, discountID uuid.UUID) ([]*Product, error)
	GetGalleryProductImages(ctx context.Context, productID uuid.UUID) ([]*ProductImage, error)
	GetMainProductImage(ctx context.Context, productID uuid.UUID) (*ProductImage, error)
	GetProduct(ctx context.Context, id uuid.UUID) (*Product, error)
	GetProductBySlug(ctx context.Context, arg *GetProductBySlugParams) (*Product, error)
	GetProductCategories(ctx context.Context, productID uuid.UUID) ([]*StoreCategory, error)
	GetProductImage(ctx context.Context, id uuid.UUID) (*ProductImage, error)
	GetProductVariant(ctx context.Context, id uuid.UUID) (*ProductVariant, error)
	GetStore(ctx context.Context, id uuid.UUID) (*Store, error)
	GetStoreBySlug(ctx context.Context, slug string) (*Store, error)
	GetStoreCategory(ctx context.Context, id uuid.UUID) (*StoreCategory, error)
	GetStoreCategoryBySlug(ctx context.Context, arg *GetStoreCategoryBySlugParams) (*StoreCategory, error)
	GetThumbnailProductImage(ctx context.Context, productID uuid.UUID) (*ProductImage, error)
	GetVariantByBarcode(ctx context.Context, arg *GetVariantByBarcodeParams) (*ProductVariant, error)
	GetVariantBySKU(ctx context.Context, arg *GetVariantBySKUParams) (*ProductVariant, error)
	GetVoucher(ctx context.Context, id uuid.UUID) (*Voucher, error)
	GetVoucherByCode(ctx context.Context, arg *GetVoucherByCodeParams) (*Voucher, error)
	GetVoucherCategories(ctx context.Context, voucherID uuid.UUID) ([]*StoreCategory, error)
	GetVoucherProducts(ctx context.Context, voucherID uuid.UUID) ([]*Product, error)
	IncrementDiscountUsage(ctx context.Context, id uuid.UUID) (*Discount, error)
	IncrementVoucherUsage(ctx context.Context, id uuid.UUID) (*Voucher, error)
	ListActiveDiscounts(ctx context.Context, arg *ListActiveDiscountsParams) ([]*Discount, error)
	ListActiveVouchers(ctx context.Context, arg *ListActiveVouchersParams) ([]*Voucher, error)
	ListDiscounts(ctx context.Context, arg *ListDiscountsParams) ([]*Discount, error)
	ListFeaturedProducts(ctx context.Context, arg *ListFeaturedProductsParams) ([]*Product, error)
	ListProductImages(ctx context.Context, productID uuid.UUID) ([]*ProductImage, error)
	ListProductVariants(ctx context.Context, productID uuid.UUID) ([]*ProductVariant, error)
	ListProducts(ctx context.Context, arg *ListProductsParams) ([]*Product, error)
	ListProductsByStatus(ctx context.Context, arg *ListProductsByStatusParams) ([]*Product, error)
	ListRootStoreCategories(ctx context.Context, storeID uuid.UUID) ([]*StoreCategory, error)
	ListStoreCategories(ctx context.Context, storeID uuid.UUID) ([]*StoreCategory, error)
	ListStoreCategoriesByParent(ctx context.Context, arg *ListStoreCategoriesByParentParams) ([]*StoreCategory, error)
	ListStores(ctx context.Context, arg *ListStoresParams) ([]*Store, error)
	ListStoresByOwner(ctx context.Context, arg *ListStoresByOwnerParams) ([]*Store, error)
	ListVariantImages(ctx context.Context, variantID uuid.NullUUID) ([]*ProductImage, error)
	ListVouchers(ctx context.Context, arg *ListVouchersParams) ([]*Voucher, error)
	RemoveAllProductCategories(ctx context.Context, productID uuid.UUID) error
	RemoveDiscountCategory(ctx context.Context, arg *RemoveDiscountCategoryParams) error
	RemoveDiscountProduct(ctx context.Context, arg *RemoveDiscountProductParams) error
	RemoveProductCategory(ctx context.Context, arg *RemoveProductCategoryParams) error
	RemoveVoucherCategory(ctx context.Context, arg *RemoveVoucherCategoryParams) error
	RemoveVoucherProduct(ctx context.Context, arg *RemoveVoucherProductParams) error
	UpdateDiscount(ctx context.Context, arg *UpdateDiscountParams) (*Discount, error)
	UpdateImageSortOrder(ctx context.Context, arg *UpdateImageSortOrderParams) error
	UpdateProduct(ctx context.Context, arg *UpdateProductParams) (*Product, error)
	UpdateProductCategories(ctx context.Context, arg *UpdateProductCategoriesParams) error
	UpdateProductImage(ctx context.Context, arg *UpdateProductImageParams) (*ProductImage, error)
	UpdateProductInventory(ctx context.Context, arg *UpdateProductInventoryParams) (*Product, error)
	UpdateProductVariant(ctx context.Context, arg *UpdateProductVariantParams) (*ProductVariant, error)
	UpdateStore(ctx context.Context, arg *UpdateStoreParams) (*Store, error)
	UpdateStoreCategory(ctx context.Context, arg *UpdateStoreCategoryParams) (*StoreCategory, error)
	UpdateVariantInventory(ctx context.Context, arg *UpdateVariantInventoryParams) (*ProductVariant, error)
	UpdateVoucher(ctx context.Context, arg *UpdateVoucherParams) (*Voucher, error)
}

var _ Querier = (*Queries)(nil)
