# This is the Traefik dynamic configuration.

http:

  # Declaring Routers
  routers:

    auth-router:
      entryPoints:
        - web
        - websecure
      service: auth-ms
      rule: "Host(`auth.theg.localhost`)"

    user-router:
      entryPoints:
        - web
        - websecure
      service: user-ms
      rule: "Host(`user.theg.localhost`)"
