# This is the Traefik dynamic configuration.

http:

  # Add the services
  services:

    auth-ms:
      loadBalancer:
        servers:
          - url: "http://auth-ms:8080"
        healthCheck:
          path: "/healthz"
          interval: 5s
          timeout: 2s
        passHostHeader: false

    user-ms:
      loadBalancer:
        servers:
          - url: "http://user-ms:8080"
        healthCheck:
          path: "/healthz"
          interval: 5s
          timeout: 2s
        passHostHeader: false
